### ISSUE TITLE
`Object` type not support now (v0.0.77)

### ISSUE THREAD

**Issue by songmingl** [broadinstitute/wdl-ide#20]
Hello, nice work! but a small question. I'm coding [under v1.0 specification](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md), but it seems that currently `Object` type is not supported. 
![image](https://user-images.githubusercontent.com/48343946/140647957-fa0f5b08-c003-4115-9698-2246677ed751.png)
Is it or just something went wrong with me?

**Comment by dinvlad** [comment]
We rely on [MiniWDL](https://github.com/chanzuckerberg/miniwdl) for WDL parsing, so I'd recommend checking with them if it's supported now or not. I remember this came up a while ago as not supported,  but worth checking again. I haven't updated `MiniWDL` dependency in a while, so if it improved support let me know.

For now though, I'd recommend switching to a custom type instead of a generic `Object`, if you have control over this WDL. IIRC the WDL developers wanted to phase out `Object`s in favor of those in the next spec.

**Comment by songmingl** [comment]
Thanks for your reply. I use `Object` since I want to read a tsv file, but I just found another way:
```
Arraay[Map[String, String]] sampleArray = read_objects(sampleList)
```
This works fine!
